### ISSUE TITLE
should use relative URL to vimeo

### ISSUE THREAD

**Issue by dholth** [RedTurtle/collective.rtvideo.vimeo#2]
In the newest Firefox https pages block embedded http content, and the video does not show.

Replace the few http://URL links in this plugin's template with //vimeo.com/... links. Or just use the iframe embed code as currently recommended by vimeo.com

This will cause the embedded object to be loaded with http or https depending on what the parent page used.

**Comment by keul** [comment]
@dholth sorry, but which version are you using? Version 0.2.0 already use `iframe` and for what I see it always provide HTTPS (that must works for HTTP domains).

**Comment by dholth** [comment]
Thanks, I must be using an outdated version.
